resources:
  repositories:
    - repository: templates
      type: github
      name: ExtendRealityLtd/DevOps
      ref: refs/tags/v3.1.0
      endpoint: ExtendRealityLtd

variables:
  - group: Build
  - group: Publish
  - group: Bot as git and GitHub user

jobs:
- template: templates/jobs/ci+cd.yml@templates
